version: '3'
services:
  async_lyceum_api:
    image: async-lyceum-api
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    volumes:
      - "lyceum-images:/images"
    networks:
      front_net:
      default:

  postgres:
    image: postgres:15.1
    restart: always
    env_file:
      - .variables.env
    networks:
      default:

networks:
  front_net:
    external: true


volumes:
  lyceum-images: