version: '3'
services:
  api:
    image: "time_api:${JOB_NAME}"
    container_name: "${JOB_NAME}_time_api"
    restart: always
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    networks:
      front_net:
      default:

  postgres:
    image: postgres
    container_name: "${JOB_NAME}_postgres"
    restart: always
    env_file:
      - .variables.env
    networks:
      default:

networks:
  front_net:
    external: true
